- app/models/matching.rb
- app/models/question.rb
- app/models/question_user.rb
- app/models/response.rb
- db/migrate/20211122164741_create_questions.rb
- db/migrate/20211122164946_create_responses.rb
- db/migrate/20211122165233_create_question_users.rb
- db/migrate/20211122170414_create_matchings.rb
- db/schema.rb
- test/models/matching_test.rb
- test/models/question_test.rb
- test/models/question_user_test.rb
- test/models/response_test.rb
> Creation de Models

- app/models/matching.rb
- app/models/profile.rb
- app/models/question.rb
- app/models/question_user.rb
- app/models/response.rb
- app/models/user.rb
- db/migrate/20211123142137_create_profiles.rb
- db/schema.rb
- test/models/profile_test.rb
> Creation models suite

- app/controllers/pages_controller.rb
- db/schema.rb
> pundit supprimé

- app/assets/stylesheets/components/_container-questionnaire.scss
- app/assets/stylesheets/components/_index.scss
- app/views/personality_questionnaires/new.html.erb
- db/schema.rb
- db/seeds.rb
CSS du formulaire modifié, non terminé.
Création d'un slider
> Changed the css of the questionnaire

- app/controllers/matches_controller.rb
- app/views/matches/launch.html.erb
- config/routes.rb
> lancement algo

- app/controllers/matches_controller.rb
- app/models/user.rb
- app/views/matches/launch.html.erb
- app/views/matches/result.html.erb
- config/routes.rb
> Algo fonctionne

- app/views/layouts/application.html.erb
- app/views/matches/result.html.erb
- app/views/messages/_message.html.erb
- app/views/shared/_footer.html.erb
> chatroom ok

- app/views/personality_questionnaires/new.html.erb
Bouton submit "valider" changé en link_to vers "launch"
> Changed button submit

- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- db/schema.rb
> rectif navbar

- app/assets/stylesheets/components/_container-questionnaire.scss
- db/schema.rb
Modifs de margins du questionnaire
> changed margins

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_logo.scss
- app/assets/stylesheets/components/_style.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> Front home

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_container-questionnaire.scss
modif des boutons et des couleurs du questionnaire
> changed colors questionnaire

- app/views/matches/result.html.erb
> branche result

- app/controllers/matches_controller.rb
- app/models/chatroom.rb
- app/models/matching.rb
- app/views/matches/picture.html.erb
- app/views/matches/result.html.erb
- db/migrate/20211129135339_add_reference_chatroom.rb
- db/schema.rb
> picture id

- app/controllers/matches_controller.rb
- app/views/matches/launch.html.erb
- app/views/shared/_footer.html.erb
- config/routes.rb
Fonctionnement if / else de la page launch.
Modification du back de la chatroom
> Modification du fonctionnement de la chatroom

- app/views/chatrooms/show.html.erb
> Picture reveal ok

- db/seeds.rb
> change-seed

- app/views/matches/result.html.erb
> Change seed

- app/controllers/matches_controller.rb
- app/models/chatroom.rb
- app/models/matching.rb
- app/views/matches/result.html.erb
> Responses matches

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_chatroom.scss
- app/assets/stylesheets/pages/_launch.scss
- app/controllers/matches_controller.rb
- app/views/chatrooms/show.html.erb
- app/views/matches/launch.html.erb
- app/views/matches/picture.html.erb
- app/views/pages/home.html.erb
> Chatroom new

- app/views/matches/launch.html.erb
- app/views/matches/result.html.erb
- db/migrate/20211201104157_add_match_column_to_questions.rb
- db/schema.rb
- db/seeds.rb
Link_to personnalisé et seed modifié
> Link_to personnalisé et seed modifié

- app/controllers/chatrooms_controller.rb
- app/views/chatrooms/show.html.erb
Le titre de la conversation correspond maintenant au nom du to_user
> Changement du titre de la conversation

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/pages/_launch.scss
- app/views/chatrooms/show.html.erb
- app/views/matches/launch.html.erb
> New btn result

- app/assets/stylesheets/components/_container-questionnaire.scss
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/personality_questionnaires/new.html.erb
> Remake questionnaire

- app/controllers/messages_controller.rb
- app/views/chatrooms/show.html.erb
> chatroom lié

- app/assets/stylesheets/pages/_result.scss
- app/views/matches/result.html.erb
Modif de l'affichage des points communs
> Modif affichage points communs

- app/views/chatrooms/show.html.erb
- app/views/messages/_message.html.erb
Modif horaire et langue chatroom
> Modif horaire et langue chatroom

- app/views/matches/picture.html.erb
Modif du wording : "partenaire" est remplacé par le nom du match.
> Modif wording page photo

- app/assets/stylesheets/components/_container-questionnaire.scss
- app/controllers/matches_controller.rb
- app/views/matches/search.html.erb
- app/views/personality_questionnaires/new.html.erb
> Loading page

- app/assets/stylesheets/pages/_result.scss
Modif css points communs : gras et plus grand
> nouvelle modif css points communs

- app/assets/stylesheets/pages/_chatroom.scss
- app/views/messages/_message.html.erb
- config/application.rb
Modification de chatroom :
-Inversion des messages selon l'utilisateur
-Couleur violette pour current-user
-Ajout de padding dans la conv
> modif back et front chatroom

- app/assets/stylesheets/pages/_chatroom.scss
- app/views/chatrooms/show.html.erb
- app/views/shared/_navbar.html.erb
> New button secret

- app/views/matches/reveal.html.erb
> Link to btn non

- app/assets/stylesheets/pages/_chatroom.scss
> Chatroom new width
